var carsList = [
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Blazer",
       "body_styles":[
          "SUV"
       ],
       "price":96989,
       "colors":[
          "blue",
          "red",
          "black",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Bolt EV",
       "body_styles":[
          "Hatchback"
       ],
       "price":130069,
       "colors":[
          "red",
          "white",
          "black",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Camaro",
       "body_styles":[
          "Coupe",
          "Convertible"
       ],
       "price":93986,
       "colors":[
          "black",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Colorado Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":146194,
       "colors":[
          "red",
          "blue",
          "black",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Colorado Extended Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":84405,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Corvette",
       "body_styles":[
          "Coupe",
          "Convertible"
       ],
       "price":119628,
       "colors":[
          "black",
          "white",
          "red",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Cruze",
       "body_styles":[
          "Sedan",
          "Hatchback"
       ],
       "price":78734,
       "colors":[
          "white",
          "black",
          "red",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Equinox",
       "body_styles":[
          "SUV"
       ],
       "price":112647,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Express 2500 Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":127099,
       "colors":[
          "black",
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Express 2500 Passenger",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":125743,
       "colors":[
          "red",
          "blue",
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Express 3500 Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":78287,
       "colors":[
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Express 3500 Passenger",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":77532,
       "colors":[
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Impala",
       "body_styles":[
          "Sedan"
       ],
       "price":81505,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Malibu",
       "body_styles":[
          "Sedan"
       ],
       "price":134920,
       "colors":[
          "blue",
          "white",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Silverado 1500 Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":144850,
       "colors":[
          "blue",
          "white",
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Silverado 1500 Double Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":71175,
       "colors":[
          "black",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Silverado 1500 LD Double Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":117530,
       "colors":[
          "black",
          "white",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Silverado 1500 Regular Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":115404,
       "colors":[
          "white",
          "blue",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Silverado 2500 HD Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":107603,
       "colors":[
          "red",
          "blue",
          "black",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Silverado 2500 HD Double Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":77571,
       "colors":[
          "black",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Silverado 2500 HD Regular Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":93616,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Silverado 3500 HD Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":81132,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Sonic",
       "body_styles":[
          "Sedan",
          "Hatchback"
       ],
       "price":97583,
       "colors":[
          "red",
          "black",
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Spark",
       "body_styles":[
          "Hatchback"
       ],
       "price":80466,
       "colors":[
          "black",
          "white",
          "red",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Suburban",
       "body_styles":[
          "SUV"
       ],
       "price":75817,
       "colors":[
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Suburban 3500HD",
       "body_styles":[
          "SUV"
       ],
       "price":98124,
       "colors":[
          "blue",
          "white",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Tahoe",
       "body_styles":[
          "SUV"
       ],
       "price":148281,
       "colors":[
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Traverse",
       "body_styles":[
          "SUV"
       ],
       "price":132215,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Trax",
       "body_styles":[
          "SUV"
       ],
       "price":80885,
       "colors":[
          "black",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Chevrolet",
       "model":"Volt",
       "body_styles":[
          "Sedan"
       ],
       "price":99434,
       "colors":[
          "blue",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"EcoSport",
       "body_styles":[
          "SUV"
       ],
       "price":98543,
       "colors":[
          "black",
          "white",
          "red",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Edge",
       "body_styles":[
          "SUV"
       ],
       "price":96175,
       "colors":[
          "red",
          "white",
          "black",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Escape",
       "body_styles":[
          "SUV"
       ],
       "price":129036,
       "colors":[
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Expedition",
       "body_styles":[
          "SUV"
       ],
       "price":126946,
       "colors":[
          "black",
          "red",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Expedition MAX",
       "body_styles":[
          "SUV"
       ],
       "price":98943,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Explorer",
       "body_styles":[
          "SUV"
       ],
       "price":110967,
       "colors":[
          "black",
          "white",
          "red",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F150 Regular Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":71610,
       "colors":[
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F150 Super Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":148292,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F150 SuperCrew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":77735,
       "colors":[
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F250 Super Duty Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":105677,
       "colors":[
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F250 Super Duty Regular Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":148597,
       "colors":[
          "black",
          "red",
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F250 Super Duty Super Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":85876,
       "colors":[
          "white",
          "red",
          "blue",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F350 Super Duty Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":115144,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F350 Super Duty Regular Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":115718,
       "colors":[
          "red",
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F350 Super Duty Super Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":142427,
       "colors":[
          "black",
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F450 Super Duty Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":72759,
       "colors":[
          "black",
          "white",
          "red",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"F450 Super Duty Regular Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":93724,
       "colors":[
          "black",
          "red",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Fiesta",
       "body_styles":[
          "Hatchback",
          "Sedan"
       ],
       "price":98910,
       "colors":[
          "black",
          "white",
          "blue",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Flex",
       "body_styles":[
          "SUV"
       ],
       "price":71542,
       "colors":[
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Fusion",
       "body_styles":[
          "Sedan"
       ],
       "price":97313,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Fusion Energi",
       "body_styles":[
          "Sedan"
       ],
       "price":118634,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Mustang",
       "body_styles":[
          "Coupe",
          "Convertible"
       ],
       "price":142761,
       "colors":[
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Ranger SuperCab",
       "body_styles":[
          "Pickup"
       ],
       "price":115713,
       "colors":[
          "red",
          "black",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Ranger SuperCrew",
       "body_styles":[
          "Pickup"
       ],
       "price":89289,
       "colors":[
          "red",
          "white",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Taurus",
       "body_styles":[
          "Sedan"
       ],
       "price":72066,
       "colors":[
          "black",
          "white",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Transit 150 Van",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":88087,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Transit 150 Wagon",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":136602,
       "colors":[
          "red",
          "blue",
          "white",
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Transit 250 Van",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":144539,
       "colors":[
          "red",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Transit 350 HD Van",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":73531,
       "colors":[
          "black",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Transit 350 Van",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":132981,
       "colors":[
          "red",
          "black",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Transit 350 Wagon",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":117031,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Transit Connect Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":113192,
       "colors":[
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Ford",
       "model":"Transit Connect Passenger",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":116006,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"370Z",
       "body_styles":[
          "Coupe",
          "Convertible"
       ],
       "price":117969,
       "colors":[
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Altima",
       "body_styles":[
          "Sedan"
       ],
       "price":113077,
       "colors":[
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Armada",
       "body_styles":[
          "SUV"
       ],
       "price":134664,
       "colors":[
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Frontier Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":113962,
       "colors":[
          "red",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Frontier King Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":146598,
       "colors":[
          "black",
          "white",
          "blue",
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"GT-R",
       "body_styles":[
          "Coupe"
       ],
       "price":74791,
       "colors":[
          "black",
          "white",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Kicks",
       "body_styles":[
          "SUV"
       ],
       "price":126911,
       "colors":[
          "red",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"LEAF",
       "body_styles":[
          "Hatchback"
       ],
       "price":91402,
       "colors":[
          "black",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Maxima",
       "body_styles":[
          "Sedan"
       ],
       "price":84654,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Murano",
       "body_styles":[
          "SUV"
       ],
       "price":127811,
       "colors":[
          "black",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"NV1500 Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":77649,
       "colors":[
          "black",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"NV200",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":95952,
       "colors":[
          "black",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"NV200 Taxi",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":108226,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"NV2500 HD Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":109837,
       "colors":[
          "black",
          "white",
          "blue",
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"NV3500 HD Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":131187,
       "colors":[
          "red",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"NV3500 HD Passenger",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":117670,
       "colors":[
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Pathfinder",
       "body_styles":[
          "SUV"
       ],
       "price":125296,
       "colors":[
          "blue",
          "white",
          "black",
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Rogue",
       "body_styles":[
          "SUV"
       ],
       "price":127271,
       "colors":[
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Rogue Sport",
       "body_styles":[
          "SUV"
       ],
       "price":131720,
       "colors":[
          "black",
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Sentra",
       "body_styles":[
          "Sedan"
       ],
       "price":128044,
       "colors":[
          "black",
          "white",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Titan Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":86968,
       "colors":[
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Titan King Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":112334,
       "colors":[
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"TITAN Single Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":84026,
       "colors":[
          "red",
          "blue",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"TITAN XD Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":123613,
       "colors":[
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"TITAN XD King Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":82032,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"TITAN XD Single Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":132660,
       "colors":[
          "black",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Versa",
       "body_styles":[
          "Sedan"
       ],
       "price":121504,
       "colors":[
          "black",
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2019,
       "make":"Nissan",
       "model":"Versa Note",
       "body_styles":[
          "Hatchback"
       ],
       "price":123860,
       "colors":[
          "black",
          "white",
          "red",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Blazer",
       "body_styles":[
          "SUV"
       ],
       "price":77877,
       "colors":[
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Bolt EV",
       "body_styles":[
          "Hatchback"
       ],
       "price":99104,
       "colors":[
          "blue",
          "white",
          "red",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Camaro",
       "body_styles":[
          "Convertible",
          "Coupe"
       ],
       "price":86169,
       "colors":[
          "red",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Colorado Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":133234,
       "colors":[
          "black",
          "white",
          "blue",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Corvette",
       "body_styles":[
          "Coupe",
          "Convertible"
       ],
       "price":98655,
       "colors":[
          "black",
          "white",
          "blue",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Equinox",
       "body_styles":[
          "SUV"
       ],
       "price":141186,
       "colors":[
          "red",
          "blue",
          "white",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Impala",
       "body_styles":[
          "Sedan"
       ],
       "price":123066,
       "colors":[
          "black",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Malibu",
       "body_styles":[
          "Sedan"
       ],
       "price":112058,
       "colors":[
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Silverado 1500 Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":117276,
       "colors":[
          "red",
          "blue",
          "white",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Silverado 1500 Regular Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":83005,
       "colors":[
          "red",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Silverado 2500 HD Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":104638,
       "colors":[
          "black",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Silverado 3500 HD Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":117129,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Spark",
       "body_styles":[
          "Hatchback"
       ],
       "price":125381,
       "colors":[
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Suburban",
       "body_styles":[
          "SUV"
       ],
       "price":143452,
       "colors":[
          "white",
          "red",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Tahoe",
       "body_styles":[
          "SUV"
       ],
       "price":81953,
       "colors":[
          "black",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Traverse",
       "body_styles":[
          "SUV"
       ],
       "price":117637,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Chevrolet",
       "model":"Trax",
       "body_styles":[
          "SUV"
       ],
       "price":139793,
       "colors":[
          "black",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"EcoSport",
       "body_styles":[
          "SUV"
       ],
       "price":136795,
       "colors":[
          "white",
          "black",
          "red",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Edge",
       "body_styles":[
          "SUV"
       ],
       "price":100790,
       "colors":[
          "red",
          "blue",
          "white",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Escape",
       "body_styles":[
          "SUV"
       ],
       "price":104701,
       "colors":[
          "black",
          "red",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Expedition",
       "body_styles":[
          "SUV"
       ],
       "price":78355,
       "colors":[
          "red",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Expedition MAX",
       "body_styles":[
          "SUV"
       ],
       "price":78632,
       "colors":[
          "blue",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Explorer",
       "body_styles":[
          "SUV"
       ],
       "price":138890,
       "colors":[
          "white",
          "red",
          "black",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"F150 Regular Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":100112,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"F150 Super Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":90163,
       "colors":[
          "white",
          "black",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"F150 SuperCrew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":104087,
       "colors":[
          "red",
          "blue",
          "white",
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"F250 Super Duty Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":105773,
       "colors":[
          "red",
          "black",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"F350 Super Duty Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":144590,
       "colors":[
          "blue",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"F450 Super Duty Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":76711,
       "colors":[
          "black",
          "red",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Fusion",
       "body_styles":[
          "Sedan"
       ],
       "price":110833,
       "colors":[
          "red",
          "black",
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Fusion Plug-in Hybrid",
       "body_styles":[
          "Sedan"
       ],
       "price":86804,
       "colors":[
          "blue",
          "red",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Mustang",
       "body_styles":[
          "Coupe",
          "Convertible"
       ],
       "price":124677,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Ranger SuperCab",
       "body_styles":[
          "Pickup"
       ],
       "price":115683,
       "colors":[
          "black",
          "white",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Ranger SuperCrew",
       "body_styles":[
          "Pickup"
       ],
       "price":125112,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Transit 250 Cargo Van",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":94318,
       "colors":[
          "black",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Transit Connect Cargo Van",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":90306,
       "colors":[
          "blue",
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Ford",
       "model":"Transit Connect Passenger Wagon",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":114644,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"370Z",
       "body_styles":[
          "Coupe"
       ],
       "price":103164,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Altima",
       "body_styles":[
          "Sedan"
       ],
       "price":97136,
       "colors":[
          "red",
          "white",
          "blue",
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Armada",
       "body_styles":[
          "SUV"
       ],
       "price":115176,
       "colors":[
          "white",
          "blue",
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"GT-R",
       "body_styles":[
          "Coupe"
       ],
       "price":126619,
       "colors":[
          "white",
          "red",
          "black"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Kicks",
       "body_styles":[
          "SUV"
       ],
       "price":73796,
       "colors":[
          "blue",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"LEAF",
       "body_styles":[
          "Hatchback"
       ],
       "price":74793,
       "colors":[
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Maxima",
       "body_styles":[
          "Sedan"
       ],
       "price":90763,
       "colors":[
          "black"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Murano",
       "body_styles":[
          "SUV"
       ],
       "price":145769,
       "colors":[
          "black",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"NV1500 Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":119719,
       "colors":[
          "black",
          "white",
          "blue",
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"NV200",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":93381,
       "colors":[
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"NV2500 HD Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":95614,
       "colors":[
          "black",
          "white",
          "blue"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"NV3500 HD Cargo",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":143832,
       "colors":[
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"NV3500 HD Passenger",
       "body_styles":[
          "Van/Minivan"
       ],
       "price":73634,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Pathfinder",
       "body_styles":[
          "SUV"
       ],
       "price":94102,
       "colors":[
          "white",
          "black",
          "blue",
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Rogue",
       "body_styles":[
          "SUV"
       ],
       "price":109096,
       "colors":[
          "blue",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Rogue Sport",
       "body_styles":[
          "SUV"
       ],
       "price":106094,
       "colors":[
          "red"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Sentra",
       "body_styles":[
          "Sedan"
       ],
       "price":88823,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Titan Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":129682,
       "colors":[
          "red",
          "blue"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Titan King Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":87804,
       "colors":[
          "red",
          "blue",
          "white"
       ],
       "transmision":"auto"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"TITAN XD Crew Cab",
       "body_styles":[
          "Pickup"
       ],
       "price":109880,
       "colors":[
          "blue",
          "white",
          "red"
       ],
       "transmision":"manual"
    },
    {
       "year":2020,
       "make":"Nissan",
       "model":"Versa",
       "body_styles":[
          "Sedan"
       ],
       "price":76798,
       "colors":[
          "red"
       ],
       "transmision":"manual"
    }
 ]