import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import BarChart from '../components/BarChart';

export async function getServerSideProps(context) {
  const res = await fetch('http://localhost:3000/api/vaccinations/country/mex');
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    }
  }

  const data2 = [
    { name: 'Simon', age: 50 },
    { name: 'Edgar', age: 40 },
    { name: 'Pablo', age: 60 },
    { name: 'Ines', age: 25 }
];

  return {
    props: { data, data2 }, // will be passed to the page component as props
  }
}


export default function Home({ data, data2 }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BarChart data={data2}/>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>

        </div>
      </main>
      <div>
        {data.map((item, index) => (
          <span key={index}>{item.people_vaccinated}</span>
        ))}
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
